/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Kerdes;
import javax.swing.JOptionPane;

/**
 *
 * @author Droti
 */
public class KerdesAdatDialog extends javax.swing.JDialog {

    private Kerdes kerdes;

    private boolean mentes;
    
   
    public boolean isMentes() {
        return mentes;
    }

    public KerdesAdatDialog(java.awt.Frame parent, boolean modal, Kerdes kerdes) {
        super(parent, modal);
        initComponents();

        setTitle("Kérdés adatok");
        setLocationRelativeTo(null);
        mentes = false;

        this.kerdes = kerdes;
        if (kerdes != null) {
           
            tfKerdes.setText(kerdes.getKerdes());
            tfv0.setText(kerdes.getValasz0());
            tfV1.setText(kerdes.getValasz1());
            tfV2.setText(kerdes.getValasz2());
            tfV3.setText(kerdes.getValasz3());

            int helyes = kerdes.getHelyesValasz();
            switch (helyes) {
                case 0:
                    rbHV0.setSelected(true);
                    break;
                case 1:
                    rbHV1.setSelected(true);
                    break;
                case 2:
                    rbHV2.setSelected(true);
                    break;
                case 3:
                    rbHV3.setSelected(true);
                    break;
            }
        } else{
            
            this.kerdes = new Kerdes();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfKerdes = new javax.swing.JTextField();
        tfv0 = new javax.swing.JTextField();
        tfV1 = new javax.swing.JTextField();
        tfV3 = new javax.swing.JTextField();
        tfV2 = new javax.swing.JTextField();
        btMentes = new javax.swing.JButton();
        btMegsem = new javax.swing.JButton();
        rbHV0 = new javax.swing.JRadioButton();
        rbHV1 = new javax.swing.JRadioButton();
        rbHV2 = new javax.swing.JRadioButton();
        rbHV3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kérdés:");

        jLabel2.setText("Válasz 1:");

        jLabel3.setText("Válasz 2: ");

        jLabel4.setText("Válasz 3:");

        jLabel5.setText("Válasz 4:");

        jLabel6.setText("Helyes válasz:");

        btMentes.setText("Mentés");
        btMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMentesActionPerformed(evt);
            }
        });

        btMegsem.setText("Mégsem");

        buttonGroup1.add(rbHV0);
        rbHV0.setText("1");

        buttonGroup1.add(rbHV1);
        rbHV1.setText("2");

        buttonGroup1.add(rbHV2);
        rbHV2.setText("3");

        buttonGroup1.add(rbHV3);
        rbHV3.setText("4");
        rbHV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHV3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbHV0)
                                .addGap(55, 55, 55)
                                .addComponent(rbHV1)
                                .addGap(50, 50, 50)
                                .addComponent(rbHV2)
                                .addGap(50, 50, 50)
                                .addComponent(rbHV3))
                            .addComponent(tfV1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfV2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfV3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfv0, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                            .addComponent(tfKerdes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btMentes)
                        .addGap(65, 65, 65)
                        .addComponent(btMegsem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfKerdes, tfV1, tfV2, tfV3, tfv0});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfv0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbHV0)
                    .addComponent(rbHV1)
                    .addComponent(rbHV2)
                    .addComponent(rbHV3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMentes)
                    .addComponent(btMegsem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMentesActionPerformed
        mentes = true;
        int helyesValasz = -1;

        if (rbHV0.isSelected()) {
            helyesValasz = 0;
        } else if (rbHV1.isSelected()) {
            helyesValasz = 1;
        } else if (rbHV2.isSelected()) {
            helyesValasz = 2;
        } else if (rbHV3.isSelected()) {
            helyesValasz = 3;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nem választott helyes választ", "Figyelmeztetés", JOptionPane.ERROR_MESSAGE);
        }

        if (helyesValasz > -1) {

            kerdes.setKerdes(tfKerdes.getText());
            kerdes.setValasz0(tfv0.getText());
            kerdes.setValasz1(tfV1.getText());
            kerdes.setValasz2(tfV2.getText());
            kerdes.setValasz3(tfV3.getText());
            kerdes.setHelyesValasz(helyesValasz);
            setVisible(false);
        }
    }//GEN-LAST:event_btMentesActionPerformed

    private void rbHV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHV3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMegsem;
    private javax.swing.JButton btMentes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbHV0;
    private javax.swing.JRadioButton rbHV1;
    private javax.swing.JRadioButton rbHV2;
    private javax.swing.JRadioButton rbHV3;
    private javax.swing.JTextField tfKerdes;
    private javax.swing.JTextField tfV1;
    private javax.swing.JTextField tfV2;
    private javax.swing.JTextField tfV3;
    private javax.swing.JTextField tfv0;
    // End of variables declaration//GEN-END:variables

    public Kerdes getKerdes() {
        return kerdes;
    }

}
